import React, { useEffect } from "react";
import Head from "next/head";
import Footer from "../../components/Footer/Footer";
import Navbar from "../../components/Navbar/Navbar";
import Subscribe from "../../components/Subscribe/Subscribe";
import { AudienceIcon, EyeIcon } from "../../components/SvgIcon/SvgIcon";
import AOS from "aos";

const About = () => {
  useEffect(() => {
    AOS.init({
      offset: 200,
      duration: 700,
    });
  }, []);
  return (
    <article className="bg-[#F5F5F5] overflow-x-hidden">
      <Head>
        <title>D’Namaz Capital - about</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="h-[25vh]"></div>
      <section className="max-w-[1400px] mx-auto px-5 md:px-10 lg:px-20">
        <div className="grid md:grid-cols-[1fr,.9fr] gap-14">
          <div className="flex justify-center flex-col">
            {/* <p className="uppercase tracking-[8px] mb-4 text-sm text-green-500 font-semibold">
              About Us{" "}
            </p> */}
            <p className="uppercase md:leading-[50px] text-xl sm:text-2xl md:text-4xl xl:text-[45px] mb-3 sm:mb-6 font-bold ">
              About Us{" "}
            </p>
            <p
              className="sm:text-xl text-justify overflow-x-hidden"
              data-aos="zoom-out"
            >
              D’Namaz Capital Limited (DCL) was established to act as
              Fund/portfolio manager in Nigeria. D’Namaz Capital Limited is
              licensed by the Securities and Exchange Commission (SEC) and
              registered under the laws of the Federal Republic of Nigeria to
              provide global Fund/Portfolio Management Services to retail and
              non-retail Investors, Non-Governmental/Non-Profit Organizations,
              Multilateral Institutions, and Government Agencies
              and Parastatals.
            </p>

            <button
              onClick={() => router.push("/open-account")}
              className="bg-[#1D5506] hover:bg-white hover:text-[#1D5506] hover:border hover:border-[#1D5506] h-[70px] font-bold text-lg w-[220px] flex justify-center items-center transition duration-200 text-white mt-6 hover:scale-105"
            >
              Get Started
            </button>
          </div>
          <div className="flex items-center" data-aos="zoom-in">
            <img src="/images/about-us.jpg" />
          </div>
        </div>
      </section>
      <section
        className="max-w-[1200px] mx-auto px-5 md:px-10 lg:px-20 mt-32"
        data-aos="fade-up"
      >
        <p className="text-center text-2xl font-semibold uppercase">
          What Distinguishes us
        </p>
        <p className="text-center sm:text-xl mt-2">
          We are Client-centric: we pride ourselves in prioritizing our
          relationship with our customers and investors who are our biggest
          assets. We therefore strive to build a strong culture that will ensure
          client satisfaction at all times.
        </p>
        <div className="grid sm:grid-cols-3 mt-24 gap-10">
          <div
            className="text-center sm:text-left bg-white p-6"
            data-aos="fade-right"
            data-aos-duration="1000"
          >
            <img className="" src="/images/mission.svg" alt="mission" />
            <p className="text-sm font-semibold text-green-900 py-3">
              Our Mission
            </p>
            <p className="text-justify">
              To help our clients realize their short and long-term financial
              and investment goals through Islamic finance.
            </p>
          </div>
          <div
            className="text-center sm:text-left bg-white p-6"
            data-aos="fade-up"
            data-aos-duration="2000"
          >
            <EyeIcon />
            <p className="text-sm font-semibold text-green-900 py-3">
              Our Vision
            </p>
            <p className="">
              To become a lifelong global leader in ethical fund management and
              a trusted ally for our clients.
            </p>
          </div>
          <div
            className="text-center sm:text-left bg-white p-6"
            data-aos="fade-down"
            data-aos-duration="3000"
          >
            <div className="flex  md:justify-start">
              <AudienceIcon />
            </div>
            <p className="text-sm font-semibold text-green-900 py-3">
              Audience
            </p>
            <p className="text-sm">
              Our target audience is ‘everyone’ irrespective of religion,
              belief, culture, status or tribe.
            </p>
          </div>
        </div>
      </section>
      <section
        className="max-w-[1500px] mx-auto sm:px-5 md:px-10 lg:px-20 mt-32 md:mb-20"
        data-aos="fade-up"
      >
        <p className="text-center text-2xl font-semibold uppercase ">
          What we provide
        </p>
        <p className="text-center sm:text-xl px-5 sm:w-1/2 mx-auto">
          Ethically backed & Shari’ah based products; sharing profit and not
          interest
        </p>
        <div>
          <div className="grid sm:grid-cols-2 mt-16">
            <div className="over-x-hidden" data-aos="flip-up">
              <img
                className="h-full w-full object-cover"
                src="/images/ethical.png"
                alt="ethics"
              />
            </div>
            <div className="bg-[#262324] p-10 flex justify-center items-center text-white ">
              <div>
                <p className="uppercase font-semibold mb-3 sm:text-[26px]">
                  ETHICAL & SHARI’AH BASED
                </p>
                <p className="sm:text-lg text-justify">
                  We share profits and do not give interest; Hence, we invest
                  your funds in ethically backed & Shari’ah compliant products.
                </p>
              </div>
            </div>
          </div>
          <div className="grid sm:grid-cols-2">
            <div className="over-x-hidden" data-aos="fade-right">
              <img
                className="h-full w-full object-cover"
                src="/images/client-centric.jpg"
                alt="customer"
              />
            </div>
            <div className="bg-[#262324] p-10  flex justify-center items-center text-white ">
              <div>
                <p className="uppercase font-semibold mb-3 sm:text-[26px]">
                  Excellent customer relations <br /> and response
                </p>
                <p className="sm:text-lg text-justify">
                  We strive to build a strong culture that will ensure client
                  satisfaction by maintaining an effective communication channel
                  with our clients and investors.
                </p>
              </div>
            </div>
          </div>
          <div className="grid sm:grid-cols-2">
            <div className="over-x-hidden" data-aos="flip-down">
              <img
                className="h-full w-full object-cover"
                src="/images/security.png"
                alt="security"
              />
            </div>
            <div className="bg-[#262324] p-10 flex justify-center items-center text-white ">
              <div>
                <p className="uppercase font-semibold mb-3 sm:text-[26px]">
                  security of your funds
                </p>
                <p className="sm:text-lg text-justify">
                  We are licensed as Fund/Portfolio Managers and so, your
                  investment is safe with us. We have also created culture and
                  environment where investors feel safe and secure to realize
                  their full wealth potentials.
                </p>
              </div>
            </div>
          </div>
          <div className="grid sm:grid-cols-2">
            <div data-aos="zoom-out" className="!over-x-hidden">
              <img
                className="h-full w-full object-cover"
                src="/images/integrity.jpg"
                alt="about 2"
              />
            </div>
            <div className="bg-[#262324] p-10 flex justify-center items-center text-white ">
              <div>
                <p className="uppercase font-semibold mb-3 sm:text-[26px]">
                  Integrity and professionalism
                </p>
                <p className="sm:text-lg text-justify">
                  We take responsibility for our words and actions and strive to
                  be independent and avoid conflicts of interest. Our clients
                  are assured of accurate and transparent information at all
                  times through an open process that helps them make informed
                  investment decisions.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="sm:pt-10 mb-16">
        <Subscribe />
      </section>
      <Footer />
    </article>
  );
};

export default About;
