import Head from "next/head";
import axios from 'axios'
import Footer from "../components/Footer/Footer";
import IndexPage from "../components/IndexPage/IndexPage";
import Navbar from "../components/Navbar/Navbar";
import Subscribe from "../components/Subscribe/Subscribe";
import Hero from "../components/Hero";
import LandingPage from "./landing-page";
import Card from "../components/Card";

// export const getStaticProps = async () => {
//   const response = await axios.get("https://dnamaz-blog.herokuapp.com/api/posts?populate=*");
//   const data = response.data;

//   return {
//     props: {
//       posts: data,
//     },
//   };
// };

const posts = []

export default function Home({ posts }) {
  return (
    <div className="bg-[#EEEEEE]">
      <Head>
        <title>D’Namaz Capital - home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>     
      {/* <Navbar /> */}
      {/* <IndexPage posts={posts} /> */}
      {/* <div className="bg-[#1D5506] h-8">
      </div> */}
      <LandingPage/>
      {/* <Card /> */}
        {/* <Hero/> */}
      {/* <Subscribe  /> */}
      {/* <Footer /> */}
    </div>
  )
}
