import React from "react";
import { useRouter } from "next/router";
import Navbar from "../../components/Navbar/Navbar";
import IndexPage from "../../components/IndexPage/IndexPage";
import Subscribe from "../../components/Subscribe/Subscribe";
import Footer from "../../components/Footer/Footer";
import Head from "next/head";

const Success = () => {
  const router = useRouter();
  return (
    <div>
      <div className="bg-[#F5F5F5]">
        <Head>
          <title>D’Namaz Capital - Open Account Form</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <div className="h-60"></div>
        <Subscribe />
        <Footer />
      </div>
      <div className="fixed z-[1000] top-0 left-0 flex justify-center w-screen h-screen bg-custom-primary bg-opacity-50">
        <div className="relative mt-20 sm:mt-32 bg-white p-5 w-full sm:w-[500px] sm:h-[400px] flex items-center">
          <div
            onClick={() => router.replace("/")}
            className="close-btn cursor-pointer"
          >
            <i className="fa-solid fa-close"></i>
          </div>
          <div className="w-4/5 mx-auto flex items-center justify-center flex-col">
            <div>
              <img
                className="w-10 mb-6"
                src="/images/successful.png"
                alt="success"
              />
            </div>
            <p className=" text-xl lg:text-2xl text-center mb-4 font-bold">
              Submitted successfully
            </p>
            <p className="text-[14px] pb-6 font-normal tracking-wider text-center max-w-[600px]">
              We are glad to inform you that your form has been successfully
              submitted to our database and that we will reach out to you in due
              course.
            </p>
            <button
              onClick={() => router.replace("/")}
              className="bg-custom-primary w-full h-14 text-white font-semibold text-base mt-8"
            >
              Go Home
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Success;
